version: '3'
services:
  client:
    build: ../client
    ports:
      - '3003:3001'
    env_file:
      - '../server/docker.env'

  server:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '../data:/data'
    env_file:
      - './docker.env'
